### ISSUE TITLE
LocationLayer 0.5.0 snapshot with navigation issue

### ISSUE THREAD

**Issue by vladgheorghe** [mapbox/mapbox-plugins-android#396]
Greetings, I see that the latest version of location layer plugin 0.5.0-SNAPSHOT does not work with either 0.11.1 navigation or 0.12.0-SNAPSHOT

Error:(122, 54) error: package com.mapbox.services.android.telemetry.location does not exist
Error:(230, 9) error: cannot find symbol class LocationEngineListener
Error:(504, 36) error: cannot find symbol variable LocationEnginePriority
Error:(609, 5) error: method does not override or implement a method from a supertype
Error:(788, 26) error: cannot find symbol variable AndroidLocationEngine
Error:(793, 36) error: cannot find symbol variable LocationEnginePriority

How can I test the newest changes in navigation ?

**Comment by rheng001** [comment]
@vladgheorghe Have the same problem.

**Comment by cammace** [comment]
The issues that 0.5.0 requires the usage of the Maps SDK 6.0.0-beta which navigation isn't currently using (since it's a beta). @danesfeder has been working on the update on the nav side of things and might have a solution for you.

**Comment by danesfeder** [comment]
Hey @vladgheorghe @rheng001, yeah @cammace is correct here.  We are currently in the process of updating the navigation repo to Maps 6.0 --> https://github.com/mapbox/mapbox-navigation-android/pull/697.  This PR will also include the 5.0 LocationLayerPlugin in our UI library, so keep an eye out for when this moves.  If you'd like you can check out that branch and try it out / see if you run into any issues.  Thanks!

**Comment by danesfeder** [comment]
Because this work can be tracked with https://github.com/mapbox/mapbox-navigation-android/pull/697 and this isn't an issue specific to the LocationLayerPlugin, I'm going to go ahead and close this.  Feel free to reopen, or cut a new ticket if you find something else.
